# Generated by Django 4.2.16 on 2026-07-14 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('sunday_service', 'Sunday Service'), ('counselling', 'Counselling Sessions'), ('baptism', 'Baptism'), ('child_dedication', 'Children Dedication'), ('wedding', 'Weddings'), ('monthly_meeting', 'Monthly General Meeting'), ('music_lessons', 'Teaching & Learning Musical Instruments'), ('holy_communion', 'Holy Communion'), ('discipleship', 'Discipleship'), ('evangelism', 'Evangelism'), ('choir', 'Choir Practice'), ('children', "Children's Sessions"), ('teenagers', 'Teenagers Sessions'), ('prayers', 'Prayers & Intercessions'), ('cleaning', 'Church Cleaning'), ('visitation', 'Elders Visitation'), ('outreach', 'Street Children Outreach'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='church/activities/')),
                ('schedule_text', models.CharField(help_text='e.g. Every Sunday 9:00 AM - 10:00 PM', max_length=200)),
                ('led_by', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200)),
                ('leader_name', models.CharField(blank=True, max_length=150)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200)),
                ('leader_name', models.CharField(blank=True, max_length=150)),
                ('started_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Compuses',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('contact_phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced')], max_length=10)),
                ('received_salvation', models.BooleanField(default=False)),
                ('salvation_when', models.CharField(blank=True, max_length=100)),
                ('salvation_where', models.CharField(blank=True, max_length=150)),
                ('salvation_meaning', models.TextField(blank=True, help_text='What does salvation mean to them')),
                ('salvation_story', models.TextField(blank=True, help_text='Who was there / what happened / brief story')),
                ('health_status', models.TextField(blank=True)),
                ('how_heard_about_church', models.CharField(blank=True, max_length=250)),
                ('reason_to_join', models.TextField(blank=True)),
                ('talents_gifts', models.TextField(blank=True)),
                ('membership_type', models.CharField(choices=[('full', 'Full Member'), ('associate', 'Associate Member')], default='full', max_length=15)),
                ('is_old_member', models.BooleanField(default=False)),
                ('prior_duration', models.CharField(blank=True, help_text='If old member, how long at the church', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='church/members/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='church.branch')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_registered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('sermon', 'Sermon'), ('teaching', 'Teaching')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('youtube_url', models.URLField()),
                ('speaker', models.CharField(blank=True, max_length=150)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('zoom', 'Zoom'), ('other', 'Other')], max_length=15)),
                ('stream_url', models.URLField()),
                ('title', models.CharField(default='Live Service', max_length=200)),
                ('is_live', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='church/library/')),
                ('external_url', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('income_category', models.CharField(blank=True, choices=[('offertory', 'Offertory'), ('tithes', 'Tithes'), ('personal_contribution', 'Personal Contributions'), ('donation', 'Donations'), ('free_will', 'Free Wills')], max_length=30)),
                ('expense_category', models.CharField(blank=True, choices=[('evangelism', 'Evangelism'), ('compuses', 'Compuses'), ('branches', 'Branches'), ('discipleship', 'Discipleship Program'), ('aff', 'AFF (Main Sponsor)'), ('visitations', 'Visitations'), ('quarterly_prayer_fasting', 'Quarterly Prayer & Fasting (Refreshments)'), ('transport', 'Transportation & Logistics'), ('water', 'Water'), ('cleaning', 'Cleaning & Sanitation'), ('monthly_prayer_fasting', 'Monthly Prayers & Fasting'), ('retreats', 'Special Retreats'), ('workshops', 'Spiritual Workshops'), ('leadership_training', 'Leadership Trainings'), ('seminars', 'Seminars'), ('crusades', 'Crusades'), ('wages', 'Wages & Salary'), ('children', 'Children Activities'), ('gym_sponsor', 'GYM (Sponsorship)'), ('media', 'Media'), ('outreach', 'Street Children Outreach Programs'), ('other', 'Other (Specify)')], max_length=30)),
                ('other_category_note', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='SSP', max_length=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.branch')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_finance_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscipleshipEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('phase_number', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Auto-set ~3 months after start', null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='ongoing', max_length=15)),
                ('facilitator', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipleship_records', to='church.member')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipleship_registered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_aboutus_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'About Us (Church)',
            },
        ),
    ]
