# Generated by Django 4.2.16 on 2026-07-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='health_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='how_heard_about_church',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced')], max_length=10),
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='occupation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='reason_to_join',
            field=models.TextField(blank=True, help_text='Why do they want to go through discipleship?'),
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='received_salvation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='salvation_meaning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='salvation_story',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='salvation_when',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='salvation_where',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='talents_gifts',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='currency',
            field=models.CharField(choices=[('SSP', 'South Sudanese Pound (SSP)'), ('USD', 'US Dollar (USD)')], default='SSP', max_length=3),
        ),
    ]
