# Generated by Django 4.2.16 on 2026-07-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_discipleshipenrollment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryresource',
            name='author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='libraryresource',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='church/library/covers/'),
        ),
    ]
