# Generated by Django 4.2.16 on 2026-08-01 18:11

import church.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church', '0003_libraryresource_author_libraryresource_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate seating / congregation capacity', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='disciples_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of disciples currently at this branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='history',
            field=models.TextField(blank=True, help_text='A brief history of how this branch was founded'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='leader_name',
            field=models.CharField(blank=True, help_text='Pastor in Charge or Elder', max_length=150),
        ),
        migrations.CreateModel(
            name='PastorElder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='church/leaders/', validators=[church.models.validate_photo_size])),
                ('role_title', models.CharField(choices=[('senior_pastor', 'Senior Pastor'), ('pastor_in_charge', 'Pastor in Charge'), ('associate_pastor', 'Associate Pastor'), ('assistant_pastor', 'Assistant Pastor'), ('elder', 'Elder'), ('deacon', 'Deacon'), ('other', 'Other (Specify)')], max_length=30)),
                ('role_title_other', models.CharField(blank=True, help_text="Only used if 'Other' is selected above", max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Optional — leave blank to keep this private', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Optional — leave blank to keep this private', max_length=254)),
                ('biography', models.TextField(help_text='A brief professional biography')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers are shown first on the public page')),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastors_elders_added', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, help_text='The branch this person serves or is serving in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaders', to='church.branch')),
            ],
            options={
                'verbose_name': 'Pastor / Elder',
                'verbose_name_plural': 'Pastors & Elders',
                'ordering': ['display_order', 'full_name'],
            },
        ),
    ]
