# Generated by Django 4.2.16 on 2026-08-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_alter_financerecord_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='expense_category',
            field=models.CharField(blank=True, choices=[('evangelism', 'Evangelism'), ('compuses', 'Compuses'), ('branches', 'Branches'), ('discipleship', 'Discipleship Program'), ('aff', 'AFF (Main Sponsor)'), ('visitations', 'Visitations'), ('quarterly_prayer_fasting', 'Quarterly Prayer & Fasting (Refreshments)'), ('transport', 'Transportation & Logistics'), ('water', 'Water'), ('cleaning', 'Cleaning & Sanitation'), ('monthly_prayer_fasting', 'Monthly Prayers & Fasting'), ('retreats', 'Special Retreats'), ('workshops', 'Spiritual Workshops'), ('leadership_training', 'Leadership Trainings'), ('seminars', 'Seminars'), ('crusades', 'Crusades'), ('wages', 'Wages & Salary'), ('children', 'Children Activities'), ('gym_sponsor', 'GYM (Sponsorship)'), ('media', 'Media'), ('outreach', 'Street Children Outreach Programs'), ('other', 'Other (Specify)')], max_length=30),
        ),
    ]
