# Generated by Django 4.2.16 on 2026-08-04 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church', '0006_alter_financerecord_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, help_text='Needed for the member to reset their own password by email', max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, help_text="This member's own login account, created at registration", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('full', 'Full Member'), ('associate', 'Associate Member'), ('online', 'Online Member')], default='full', max_length=15),
        ),
    ]
