# Generated by Django 4.2.16 on 2026-08-07 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church', '0007_member_email_member_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(blank=True, help_text='Shown to anonymous submitters to check for a response later', max_length=20, unique=True)),
                ('submitted_by_name', models.CharField(blank=True, help_text='Optional — leave blank to stay anonymous', max_length=150)),
                ('contact_phone', models.CharField(blank=True, help_text="Optional — only if you'd like someone to follow up with you", max_length=20)),
                ('request_text', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted — Awaiting Review'), ('forwarded', 'Forwarded to Superadmin'), ('responded', 'Responded')], default='submitted', max_length=15)),
                ('response_text', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests', to='church.member')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_responses', to=settings.AUTH_USER_MODEL)),
                ('submitted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=20)),
                ('topic', models.CharField(blank=True, help_text="General topic only, optional - e.g. 'marriage', 'grief'. No need for details here.", max_length=200)),
                ('preferred_date', models.DateField(help_text='Your preferred date for the session')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('queue_position', models.PositiveIntegerField(blank=True, help_text="Order within that day's queue - assigned automatically", null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested - Awaiting Scheduling'), ('scheduled', 'Scheduled'), ('current', 'Now Being Seen'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling_sessions_booked', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling_sessions', to='church.member')),
                ('scheduled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling_sessions_scheduled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date', 'queue_position', '-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(help_text='Total number who attended')),
                ('notes', models.CharField(blank=True, help_text="e.g. 'Easter Sunday', 'combined service'", max_length=250)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='church.branch')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='counselingsession',
            constraint=models.UniqueConstraint(fields=('scheduled_date', 'queue_position'), name='unique_counseling_queue_slot'),
        ),
        migrations.AddConstraint(
            model_name='counselingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'current')), fields=('scheduled_date',), name='one_current_counseling_session_per_date'),
        ),
    ]
