# Generated by Django 4.2.16 on 2026-08-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_prayerrequest_counselingsession_attendancerecord_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counselingsession',
            options={'ordering': ['scheduled_slot', '-requested_at']},
        ),
        migrations.RemoveConstraint(
            model_name='counselingsession',
            name='unique_counseling_queue_slot',
        ),
        migrations.RemoveConstraint(
            model_name='counselingsession',
            name='one_current_counseling_session_per_date',
        ),
        migrations.RemoveField(
            model_name='counselingsession',
            name='queue_position',
        ),
        migrations.RemoveField(
            model_name='counselingsession',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='counselingsession',
            name='scheduled_slot',
            field=models.DateTimeField(blank=True, help_text='The confirmed one-hour slot, Monday or Wednesday between 8AM and 4PM', null=True),
        ),
        migrations.AlterField(
            model_name='counselingsession',
            name='preferred_date',
            field=models.DateField(help_text='Your preferred date - sessions run Mondays and Wednesdays, 8AM-4PM'),
        ),
        migrations.AddConstraint(
            model_name='counselingsession',
            constraint=models.UniqueConstraint(fields=('scheduled_slot',), name='unique_counseling_slot'),
        ),
    ]
