# Generated by Django 4.2.16 on 2026-08-17 13:16

import church.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church', '0009_alter_counselingsession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('bank', 'Bank Account'), ('momo', 'Mobile Money')], max_length=10)),
                ('label', models.CharField(help_text="e.g. 'Main Offering Account' or 'MTN Mobile Money'", max_length=150)),
                ('currency', models.CharField(choices=[('SSP', 'South Sudanese Pound (SSP)'), ('USD', 'US Dollar (USD)')], default='SSP', max_length=3)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('account_name', models.CharField(blank=True, help_text='Name the account is registered under', max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('branch_name', models.CharField(blank=True, help_text='Bank branch, if applicable', max_length=150)),
                ('swift_code', models.CharField(blank=True, help_text='For international transfers, if applicable', max_length=20)),
                ('momo_provider', models.CharField(blank=True, help_text='e.g. MTN Mobile Money, Digitel Money', max_length=100)),
                ('momo_number', models.CharField(blank=True, max_length=20)),
                ('momo_registered_name', models.CharField(blank=True, help_text='Name the mobile money line is registered under', max_length=150)),
                ('instructions', models.TextField(blank=True, help_text='Optional note for givers, e.g. what reference to use')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers are shown first on the public Give page')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from the public Give page without deleting it')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving_accounts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giving Account (Bank / MoMo)',
                'verbose_name_plural': 'Giving Accounts (Bank / MoMo)',
                'ordering': ['display_order', 'account_type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='GivingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giver_name', models.CharField(blank=True, help_text='Optional — leave blank to give anonymously', max_length=150)),
                ('contact_phone', models.CharField(blank=True, help_text="Optional — only if you'd like a receipt or follow-up", max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('purpose', models.CharField(choices=[('tithe', 'Tithe'), ('offertory', 'Offertory'), ('donation', 'Donation'), ('free_will', 'Free Will Offering'), ('other', 'Other')], default='donation', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('SSP', 'South Sudanese Pound (SSP)'), ('USD', 'US Dollar (USD)')], default='SSP', max_length=3)),
                ('transaction_reference', models.CharField(blank=True, help_text='Bank deposit slip / mobile money transaction ID, if you have one', max_length=100)),
                ('proof_of_payment', models.ImageField(blank=True, help_text='Optional — a screenshot or photo of the payment confirmation', null=True, upload_to='church/giving/proofs/', validators=[church.models.validate_photo_size])),
                ('message', models.TextField(blank=True, help_text='Optional note to the church')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, help_text='e.g. reason for rejecting', max_length=250)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('finance_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving_record', to='church.financerecord')),
                ('given_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving_records', to=settings.AUTH_USER_MODEL)),
                ('giving_account', models.ForeignKey(blank=True, help_text='Which bank / mobile money account the funds were sent to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving_records', to='church.givingaccount')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving_records', to='church.member')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving_records_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giving / Donation Record',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
