# Generated by Django 4.2.16 on 2026-08-18 20:47

import church.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_givingaccount_givingrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='church/library/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'epub', 'doc', 'docx', 'ppt', 'pptx', 'txt'], message='Unsupported file type. Allowed: PDF, EPUB, DOC(X), PPT(X), TXT.'), church.models.validate_library_file_size]),
        ),
    ]
