# Generated by Django 4.2.16 on 2026-08-26 20:48

import church.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_alter_libraryresource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='church/activities/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Unsupported image type. Allowed: JPG, JPEG, PNG, WEBP.')]),
        ),
        migrations.AlterField(
            model_name='givingrecord',
            name='proof_of_payment',
            field=models.ImageField(blank=True, help_text='Optional — a screenshot or photo of the payment confirmation', null=True, upload_to='church/giving/proofs/', validators=[church.models.validate_photo_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Unsupported image type. Allowed: JPG, JPEG, PNG, WEBP.')]),
        ),
        migrations.AlterField(
            model_name='libraryresource',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='church/library/covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Unsupported image type. Allowed: JPG, JPEG, PNG, WEBP.')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='church/members/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Unsupported image type. Allowed: JPG, JPEG, PNG, WEBP.')]),
        ),
        migrations.AlterField(
            model_name='pastorelder',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='church/leaders/', validators=[church.models.validate_photo_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Unsupported image type. Allowed: JPG, JPEG, PNG, WEBP.')]),
        ),
    ]
