# Generated by Django 4.2.16 on 2026-08-29 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0012_alter_activity_image_and_more'),
        ('aff', '0005_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0003_alter_schoolactivity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('church', 'Church (ACC)'), ('gym', 'Global Youth Ministry'), ('aff', "Apostles' Feet Foundation")], max_length=10)),
                ('title', models.CharField(help_text='Snapshot of the activity/event name at submission time', max_length=200)),
                ('category', models.CharField(help_text="Snapshot of the activity's category at submission time", max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('SSP', 'South Sudanese Pound (SSP)'), ('USD', 'US Dollar (USD)')], default='SSP', max_length=3)),
                ('justification', models.TextField(help_text='Why this activity needs this budget')),
                ('status', models.CharField(choices=[('submitted', 'Submitted — Awaiting Finance Review'), ('forwarded', 'Forwarded to Superadmin'), ('returned', 'Returned — Needs Changes'), ('approved', 'Approved')], default='submitted', max_length=15)),
                ('returned_by', models.CharField(blank=True, choices=[('finance', 'Finance Admin'), ('superadmin', 'Superadmin')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aff_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='aff.activity')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_approved', to=settings.AUTH_USER_MODEL)),
                ('church_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='church.activity')),
                ('forwarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_forwarded', to=settings.AUTH_USER_MODEL)),
                ('gym_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='gym.schoolactivity')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('forwarded', 'Forwarded to Superadmin'), ('approved', 'Approved'), ('returned', 'Returned'), ('resubmitted', 'Resubmitted'), ('comment', 'Comment')], default='comment', max_length=15)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='finance.budget')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
