# Generated by Django 4.2.16 on 2026-07-14 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('request_date', models.DateField()),
                ('tel', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('single', 'Single')], max_length=10)),
                ('residential_address', models.CharField(max_length=250)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('family', models.CharField(blank=True, max_length=250)),
                ('membership_type', models.CharField(choices=[('full_time', 'Full Time Member'), ('associate', 'Associate Member')], max_length=15)),
                ('membership_duration', models.CharField(blank=True, max_length=100)),
                ('received_salvation', models.BooleanField(default=False)),
                ('salvation_when_where', models.CharField(blank=True, max_length=250)),
                ('salvation_experience', models.TextField(blank=True)),
                ('gone_through_discipleship', models.BooleanField(default=False)),
                ('department_serving', models.CharField(blank=True, max_length=150)),
                ('how_church_can_help', models.TextField()),
                ('need_category', models.CharField(choices=[('school_fees', 'School Fees'), ('tuition', 'Tuition Fees'), ('medical', 'Medical Bills'), ('transport', 'Transportation'), ('rent', 'Rent'), ('feeding', 'Feeding'), ('other', 'Other (Specify)')], max_length=20)),
                ('other_need_note', models.CharField(blank=True, max_length=200)),
                ('amount_have', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('help_directed_to', models.CharField(choices=[('me', 'Me'), ('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('others', 'Others')], max_length=10)),
                ('help_directed_other', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('disbursed', 'Disbursed')], default='pending', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('disbursed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aff_requests_filled', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aff_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense (Disbursement)')], max_length=10)),
                ('income_category', models.CharField(blank=True, choices=[('church_donor', 'Church ACC (Main Donor)'), ('donations_grants', 'Donations & Grants'), ('free_will', 'Free Will'), ('other', 'Other (Specify)')], max_length=30)),
                ('other_category_note', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='SSP', max_length=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aff_finance_records', to=settings.AUTH_USER_MODEL)),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries', to='aff.assistancerequest')),
            ],
        ),
        migrations.CreateModel(
            name='CashReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash_at_hand', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(help_text='Where this cash came from', max_length=250)),
                ('system_recorded_balance', models.DecimalField(decimal_places=2, help_text='System total at time of check', max_digits=12)),
                ('discrepancy', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aff_aboutus_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'About Us (AFF)',
            },
        ),
    ]
