# Generated by Django 4.2.16 on 2026-07-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='currency',
            field=models.CharField(choices=[('SSP', 'South Sudanese Pound (SSP)'), ('USD', 'US Dollar (USD)')], default='SSP', max_length=3),
        ),
        migrations.AddField(
            model_name='cashreconciliation',
            name='currency',
            field=models.CharField(choices=[('SSP', 'South Sudanese Pound (SSP)'), ('USD', 'US Dollar (USD)')], default='SSP', max_length=3),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='currency',
            field=models.CharField(choices=[('SSP', 'South Sudanese Pound (SSP)'), ('USD', 'US Dollar (USD)')], default='SSP', max_length=3),
        ),
    ]
