# Generated by Django 4.2.16 on 2026-08-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aff', '0002_assistancerequest_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('info_needed', 'More Information Needed'), ('disbursed', 'Disbursed')], default='pending', max_length=15),
        ),
    ]
