# Generated by Django 4.2.16 on 2026-08-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aff', '0003_alter_assistancerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='membership_type',
            field=models.CharField(choices=[('full_time', 'Full Time Member'), ('associate', 'Associate Member'), ('online', 'Online Member')], max_length=15),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted — Awaiting AFF Review'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('info_needed', 'More Information Needed'), ('disbursed', 'Disbursed')], default='pending', max_length=15),
        ),
    ]
