# Generated by Django 4.2.16 on 2026-08-29 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aff', '0004_alter_assistancerequest_membership_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('program', 'Support Program'), ('outreach', 'Community Outreach'), ('training', 'Training & Mentorship'), ('community_event', 'Community Event'), ('administrative', 'Administrative'), ('fundraising', 'Fundraising'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='aff/activities/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Unsupported image type. Allowed: JPG, JPEG, PNG, WEBP.')])),
                ('schedule_text', models.CharField(blank=True, help_text='e.g. Every last Saturday of the month', max_length=200)),
                ('led_by', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
