# Generated by Django 4.2.16 on 2026-08-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('church_info', 'Church - Information Admin'), ('church_finance', 'Church - Finance Admin'), ('church_membership', 'Church - Membership Admin'), ('church_discipleship', 'Church - Discipleship Admin'), ('church_media', 'Church - Live/Media Admin'), ('gym_info', 'GYM - Information Admin'), ('gym_finance', 'GYM - Finance Admin'), ('gym_schools', 'GYM - Schools Admin'), ('gym_media', 'GYM - Media Admin'), ('aff_info', 'AFF - Information Admin'), ('aff_finance', 'AFF - Finance Admin'), ('member', 'Church Member')], default='member', max_length=30),
        ),
    ]
