# Generated by Django 4.2.16 on 2026-08-18 22:11

import accounts.fields
from django.db import migrations


def encrypt_existing_totp_secrets(apps, schema_editor):
    """One-time migration of any totp_secret values written before this field
    was encrypted. Uses raw SQL on both ends — reading old plaintext and
    writing the new ciphertext — so it can't accidentally run through
    EncryptedCharField.get_prep_value() twice and double-encrypt."""
    from accounts.fields import _get_fernet

    fernet = _get_fernet()
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, totp_secret FROM accounts_user WHERE totp_secret != ''")
        rows = cursor.fetchall()
        for user_id, value in rows:
            try:
                fernet.decrypt(value.encode())
                continue  # already encrypted (e.g. re-running against a fresh DB)
            except Exception:
                pass
            encrypted = fernet.encrypt(value.encode()).decode()
            cursor.execute("UPDATE accounts_user SET totp_secret = %s WHERE id = %s", [encrypted, user_id])


def decrypt_totp_secrets(apps, schema_editor):
    """Reverse — best-effort, for migrating backwards during development only."""
    from accounts.fields import _get_fernet
    from cryptography.fernet import InvalidToken

    fernet = _get_fernet()
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, totp_secret FROM accounts_user WHERE totp_secret != ''")
        rows = cursor.fetchall()
        for user_id, value in rows:
            try:
                plain = fernet.decrypt(value.encode()).decode()
            except InvalidToken:
                continue
            cursor.execute("UPDATE accounts_user SET totp_secret = %s WHERE id = %s", [plain, user_id])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_totp_secret_user_two_factor_backup_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=accounts.fields.EncryptedCharField(blank=True, help_text='Encrypted at rest — see accounts.fields.EncryptedCharField', max_length=255),
        ),
        migrations.RunPython(encrypt_existing_totp_secrets, decrypt_totp_secrets),
    ]
