# Generated by Django 4.2.16 on 2026-07-14 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('main', 'Main (All Sites)'), ('church', 'Church (ACC)'), ('gym', 'Global Youth Ministry'), ('aff', "Apostles' Feet Foundation")], max_length=10)),
                ('item_type', models.CharField(choices=[('news', 'News'), ('event', 'Upcoming Event'), ('reminder', 'Reminder'), ('encouragement', 'Daily Encouragement'), ('recent', 'Recently Done'), ('live', 'Live Now')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(help_text='Short teaser shown on the feed card', max_length=300)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsfeed/')),
                ('event_date', models.DateTimeField(blank=True, help_text='For events/reminders', null=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Live items are auto-pinned')),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(help_text='Item is hidden automatically after this time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
    ]
