# Generated by Django 4.2.16 on 2026-07-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='scope',
            field=models.CharField(choices=[('main', 'Main (All Sites)'), ('church', 'Church (ACC)'), ('aff', "Apostles' Feet Foundation")], max_length=10),
        ),
    ]
