# Generated by Django 4.2.16 on 2026-08-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_alter_feeditem_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='scope',
            field=models.CharField(choices=[('main', 'Main (All Sites)'), ('church', 'Church (ACC)'), ('gym', 'Global Youth Ministry'), ('aff', "Apostles' Feet Foundation")], max_length=10),
        ),
    ]
