# Generated by Django 4.2.16 on 2026-08-26 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_alter_feeditem_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Keep this item visible indefinitely, ignoring its expiry date'),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Item is hidden automatically after this time. Leave blank if Featured.', null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newsfeed/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Unsupported image type. Allowed: JPG, JPEG, PNG, WEBP.')]),
        ),
    ]
