# Generated by Django 4.2.16 on 2026-08-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='scope',
            field=models.CharField(choices=[('church', 'Church (ACC)'), ('gym', 'Global Youth Ministry'), ('aff', "Apostles' Feet Foundation"), ('system', 'System')], max_length=10),
        ),
    ]
