# Generated by Django 4.2.16 on 2026-07-14 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('role_description', models.CharField(blank=True, max_length=200)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='gym.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('class_grade', models.CharField(blank=True, max_length=50)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gym.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDisciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phase_number', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('status', models.CharField(default='ongoing', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciples', to='gym.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('club', 'School Club Grams'), ('internship_discipleship', 'Internship Discipleship'), ('purpose_conference', 'Purpose Driven Conferences'), ('teachers_conference', 'Teachers Conferences'), ('trauma_awareness', 'Trauma Awareness & Counselling'), ('counselling', 'Counselling'), ('prayers_fasting', 'Prayers & Fasting'), ('leadership_training', 'Leadership Trainings'), ('leadership_meeting', 'Leadership Meetings'), ('fellowship', 'Monthly Fellowship'), ('incentives', 'Incentives & Support'), ('volunteer_refresher', 'Volunteer Refresher Training'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gym/activities/')),
                ('date', models.DateField(blank=True, null=True)),
                ('schedule_text', models.CharField(blank=True, max_length=200)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='gym.school')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('income_category', models.CharField(blank=True, choices=[('donation', 'Donation'), ('church', 'Church (ACC)'), ('free_will', 'Free Will')], max_length=30)),
                ('expense_category', models.CharField(blank=True, choices=[('activities', 'Activities'), ('office_maintenance', 'Office Maintenance'), ('media', 'Media'), ('transport', 'Transportation'), ('stationery', 'Stationery Items'), ('cleaning', 'Cleaning & Sanitation'), ('other', 'Other (Specify)')], max_length=30)),
                ('other_category_note', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='SSP', max_length=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_finance_records', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.school')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_aboutus_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'About Us (GYM)',
            },
        ),
    ]
