# Generated by Django 4.2.16 on 2026-08-26 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_financerecord_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolactivity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gym/activities/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Unsupported image type. Allowed: JPG, JPEG, PNG, WEBP.')]),
        ),
    ]
